### ISSUE TITLE
Jenkins treats empty result junit.xml as a failure

### ISSUE THREAD

**Issue by quarckster** [RedHatInsights/insights-pipeline-lib#75]
If smoke tests don't have `parallel` mark `iqeParallelCommand` will produce junit.xml without result. According to https://support.cloudbees.com/hc/en-us/articles/204746880-Recieving-exception-hudson-AbortException-None-of-the-test-reports-contained-any-result Jenkins treats it as a failure.

**Actual result:**
Smoke tests job fails if there are no parallel tests.

**Expected result:**
Smoke tests job shouldn't fail if there no parallel tests.

**Comment by RonnyPfannschmidt** [comment]
pytest itself should already consider this a failed testun, i propose not considering artifact when considering a no tests failed pytest as passed for optional parallel runs

**Comment by bsquizz** [comment]
Let me know if this fixes the problem: https://github.com/RedHatInsights/insights-pipeline-lib/commit/6f7591d9b222c9d51e49662f9ecc8c4395089d81

**Comment by quarckster** [comment]
@bsquizz thanks, it's fixed the issue.
